subdir-ccflags-y += \
	-I$(src)/linux/include \
	-I$(src)/linux/pri/include \
	-I$(src)/core/include \
	-I$(src)/include \
	-I$(src)/mt6572/include \
	-I$(src)/../detect_inc \
	-I$(src)/../btif/inc \
	-I$(src)/../compat_inc

obj-m += mtk_stp_wmt_soc.o
mtk_stp_wmt_soc-objs := core/wmt_core.o core/wmt_ctrl.o core/wmt_func.o \
	core/wmt_ic_soc.o core/wmt_lib.o core/wmt_conf.o \
	linux/pri/wmt_dev.o linux/pri/wmt_exp.o \
	linux/pri/stp_btif.o \
	linux/pub/osal.o linux/pub/bgw_desense.o \
	linux/pri/stp_exp.o core/stp_core.o core/psm_core.o core/btm_core.o \
	linux/pri/stp_dbg.o \
	mt6572/mtk_wcn_consys_hw.o mt6572/wmt_plat_alps.o mt6572/plat_stub.o

obj-m += mtk_stp_bt_soc.o
mtk_stp_bt_soc-objs := linux/pub/stp_chrdev_bt.o

obj-m += mtk_wmt_wifi_soc.o
mtk_wmt_wifi_soc-objs := linux/pub/wmt_chrdev_wifi.o
